### TEST GET /
GET http://localhost:5003

### POST: Register a user (Test 03)
POST http://localhost:5003/auth/register
Content-Type: application/json

{
    "username": "test@gmail.com",
    "password": "123456"
}

### POST login a user
POST http://localhost:5003/auth/login
Content-Type: application/json

{
    "username": "test@gmail.com",
    "password": "123456"
}

### GET get all todos (protected)
GET http://localhost:5003/todos 
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzY2OTkwODk3LCJleHAiOjE3NjcwNzcyOTd9.TVZ3E6VuOl1bUvZqhJ1RohT5qKV4wcED7io4WDMlolA

### POST create a todo
POST http://localhost:5003/todos
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzY2OTkwODk3LCJleHAiOjE3NjcwNzcyOTd9.TVZ3E6VuOl1bUvZqhJ1RohT5qKV4wcED7io4WDMlolA
Content-Type: application/json

{
    "task": "test task 02"
}
